name: Build & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
    
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential ninja-build gcc python3-pip
          pip install --user meson==1.6.1

      - name: Configure PATH
        run: echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV

      - name: Configure Meson
        run: meson setup build

      - name: Build
        run: meson compile -C build

      - name: Test
        run: meson test -C build --verbose
